### PR TITLE
DO NOT MERGE: Test

### PR DESCRIPTION
**Pull request by indraraj**

### CODE REVIEW

**Comment by indraraj** [comment]
@karelhala @ryelo can you add me as Collaborator to this repo.

**Comment by karelhala** [comment]
I'm gonna leave this on Ryan as he can add outside collaborators to the repo. Just curious, why do you need access? There's a deploy key set up which should be just fine for releasing the code.

**Comment by indraraj** [comment]
> I'm gonna leave this on Ryan as he can add outside collaborators to the repo. Just curious, why do you need access? There's a deploy key set up which should be just fine for releasing the code.

Honestly, I am not sure about usage at the moment. I am just following the setup doc to get the repo access, which I think @uidoyen  from my team already got.

**Comment by karelhala** [comment]
@indraraj well the access is not really required, unless you want to do something with the repository. The problem is that each outside collaborator cost something extra, so we want to avoid this as much as possible.

That said, the deployment should utilize deploy token (which is already working).

And sorry for such a late reply, I thought I hit send the other day, but turns out I forgot.

**Comment by indraraj** [comment]
> @indraraj well the access is not really required, unless you want to do something with the repository. The problem is that each outside collaborator cost something extra, so we want to avoid this as much as possible.
> 
> That said, the deployment should utilize deploy token (which is already working).
> 
> And sorry for such a late reply, I thought I hit send the other day, but turns out I forgot.

Hey np, it's good. Will see later if the need arises.

**Comment by karelhala** [comment]
@indraraj all the pushes should be automatic to the build repository, hence the usage of deploy key. If you need to regenerate it let me know!

**Pull request closed without merging**
